name: Connect to EC2 and Download Files

on:
  push:
    branches:
      - main

jobs:
  connect-and-download:
    runs-on: ubuntu-latest
    container:
      image: assassin010/ubuntu:ubuntu-latest-plus

    steps:
      - name: Debug Info
        run: |
          docker version
          uname -a
          cat /etc/os-release
          cat /proc/cpuinfo

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Session Manager Plugin
        run: |
          echo "Downloading Session Manager Plugin..."
          curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
          echo "Installing Session Manager Plugin..."
          dpkg -i session-manager-plugin.deb

      - name: Verify Session Manager Plugin Installation
        run: |
          echo "Verifying Session Manager Plugin installation..."
          session_manager_plugin_version=$(session-manager-plugin --version 2>&1)
          echo "Session Manager Plugin version: $session_manager_plugin_version"
        
      - name: Configure AWS CLI
        run: |
          echo "Configuring AWS CLI..."
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_DEFAULT_REGION=us-east-1

      - name: Create SSM Document
        run: |
          echo -n "$(cat ssm_document1.json | jq -c)" > ssm_document_content1.json
          echo -n "$(cat ssm_document2.json | jq -c)" > ssm_document_content2.json

      - name: Run SSM Document NON GIT
        run: |
          instance_id="i-05aae421de061543f"
          echo "Connecting to EC2 Instance..."
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --instance-ids $instance_id \
            --timeout-seconds 18000 \
            --max-concurrency "50" \
            --max-errors "0" \
            --parameters workingDirectory="/",executionTimeout="18000" \
            --output-s3-bucket-name "pocgithubactions" \
            --cloud-watch-output-config "CloudWatchOutputEnabled=true,CloudWatchLogGroupName=non-git" \
            --cli-input-json "$(cat ssm_document_content1.json)"
            --service-role-arn "arn:aws:iam::955769636964:role/SNS_Role" \    
            #--notification-config "NotificationArn=arn:aws:sns:us-east-1:955769636964:ssm_execution_status,NotificationEvents=All,NotificationType=Command"
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: us-east-1  
            
      - name: Run SSM Document GIT
        run: |
          instance_id="i-05aae421de061543f"
          echo "Connecting to EC2 Instance..."
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --instance-ids $instance_id \
            --timeout-seconds 18000 \
            --max-concurrency "50" \
            --max-errors "0" \
            --parameters workingDirectory="/",executionTimeout="18000" \
            --output-s3-bucket-name "pocgithubactions" \
            --cloud-watch-output-config "CloudWatchOutputEnabled=true,CloudWatchLogGroupName=git" \
            --cli-input-json "$(cat ssm_document_content2.json)"
            --service-role-arn "arn:aws:iam::955769636964:role/SNS_Role" \    
            #--notification-config "NotificationArn=arn:aws:sns:us-east-1:955769636964:ssm_execution_status,NotificationEvents=All,NotificationType=Command"            
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: us-east-1  
          
  cleanup:
    runs-on: ubuntu-latest
    needs: connect-and-download
    if: ${{ always() }}  # Ensure cleanup runs even if the previous job fails
    steps:
      - name: Cleanup
        run: |
          # Retrieve the stored container ID
          container_id=${{ needs.connect-and-download.outputs.container_id }}
          if [ -n "$container_id" ]; then
            # Use the container ID in the cleanup command
            docker exec $container_id sh -c "cat /etc/*release | grep ^ID"
          else
            echo "Container ID not found."
          fi
